// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: proto/shop.proto

package GoShop

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GoShopServiceClient is the client API for GoShopService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GoShopServiceClient interface {
	CreateCustomer(ctx context.Context, in *CustomerDetails, opts ...grpc.CallOption) (*CustomerResponse, error)
}

type goShopServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGoShopServiceClient(cc grpc.ClientConnInterface) GoShopServiceClient {
	return &goShopServiceClient{cc}
}

func (c *goShopServiceClient) CreateCustomer(ctx context.Context, in *CustomerDetails, opts ...grpc.CallOption) (*CustomerResponse, error) {
	out := new(CustomerResponse)
	err := c.cc.Invoke(ctx, "/goshop.GoShopService/CreateCustomer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoShopServiceServer is the server API for GoShopService service.
// All implementations must embed UnimplementedGoShopServiceServer
// for forward compatibility
type GoShopServiceServer interface {
	CreateCustomer(context.Context, *CustomerDetails) (*CustomerResponse, error)
	mustEmbedUnimplementedGoShopServiceServer()
}

// UnimplementedGoShopServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGoShopServiceServer struct {
}

func (UnimplementedGoShopServiceServer) CreateCustomer(context.Context, *CustomerDetails) (*CustomerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCustomer not implemented")
}
func (UnimplementedGoShopServiceServer) mustEmbedUnimplementedGoShopServiceServer() {}

// UnsafeGoShopServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoShopServiceServer will
// result in compilation errors.
type UnsafeGoShopServiceServer interface {
	mustEmbedUnimplementedGoShopServiceServer()
}

func RegisterGoShopServiceServer(s grpc.ServiceRegistrar, srv GoShopServiceServer) {
	s.RegisterService(&GoShopService_ServiceDesc, srv)
}

func _GoShopService_CreateCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomerDetails)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoShopServiceServer).CreateCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goshop.GoShopService/CreateCustomer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoShopServiceServer).CreateCustomer(ctx, req.(*CustomerDetails))
	}
	return interceptor(ctx, in, info, handler)
}

// GoShopService_ServiceDesc is the grpc.ServiceDesc for GoShopService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GoShopService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "goshop.GoShopService",
	HandlerType: (*GoShopServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCustomer",
			Handler:    _GoShopService_CreateCustomer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/shop.proto",
}
