// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: proto/task.proto

package GoTask

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GoTaskServiceClient is the client API for GoTaskService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GoTaskServiceClient interface {
	CreateCustomer(ctx context.Context, in *CustomerDetails, opts ...grpc.CallOption) (*CustomerResponse, error)
	InsertToken(ctx context.Context, in *Token, opts ...grpc.CallOption) (*TokenResponse, error)
}

type goTaskServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGoTaskServiceClient(cc grpc.ClientConnInterface) GoTaskServiceClient {
	return &goTaskServiceClient{cc}
}

func (c *goTaskServiceClient) CreateCustomer(ctx context.Context, in *CustomerDetails, opts ...grpc.CallOption) (*CustomerResponse, error) {
	out := new(CustomerResponse)
	err := c.cc.Invoke(ctx, "/GoTask.GoTaskService/CreateCustomer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goTaskServiceClient) InsertToken(ctx context.Context, in *Token, opts ...grpc.CallOption) (*TokenResponse, error) {
	out := new(TokenResponse)
	err := c.cc.Invoke(ctx, "/GoTask.GoTaskService/InsertToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoTaskServiceServer is the server API for GoTaskService service.
// All implementations must embed UnimplementedGoTaskServiceServer
// for forward compatibility
type GoTaskServiceServer interface {
	CreateCustomer(context.Context, *CustomerDetails) (*CustomerResponse, error)
	InsertToken(context.Context, *Token) (*TokenResponse, error)
	mustEmbedUnimplementedGoTaskServiceServer()
}

// UnimplementedGoTaskServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGoTaskServiceServer struct {
}

func (UnimplementedGoTaskServiceServer) CreateCustomer(context.Context, *CustomerDetails) (*CustomerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCustomer not implemented")
}
func (UnimplementedGoTaskServiceServer) InsertToken(context.Context, *Token) (*TokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertToken not implemented")
}
func (UnimplementedGoTaskServiceServer) mustEmbedUnimplementedGoTaskServiceServer() {}

// UnsafeGoTaskServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoTaskServiceServer will
// result in compilation errors.
type UnsafeGoTaskServiceServer interface {
	mustEmbedUnimplementedGoTaskServiceServer()
}

func RegisterGoTaskServiceServer(s grpc.ServiceRegistrar, srv GoTaskServiceServer) {
	s.RegisterService(&GoTaskService_ServiceDesc, srv)
}

func _GoTaskService_CreateCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomerDetails)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoTaskServiceServer).CreateCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GoTask.GoTaskService/CreateCustomer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoTaskServiceServer).CreateCustomer(ctx, req.(*CustomerDetails))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoTaskService_InsertToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Token)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoTaskServiceServer).InsertToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GoTask.GoTaskService/InsertToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoTaskServiceServer).InsertToken(ctx, req.(*Token))
	}
	return interceptor(ctx, in, info, handler)
}

// GoTaskService_ServiceDesc is the grpc.ServiceDesc for GoTaskService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GoTaskService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "GoTask.GoTaskService",
	HandlerType: (*GoTaskServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCustomer",
			Handler:    _GoTaskService_CreateCustomer_Handler,
		},
		{
			MethodName: "InsertToken",
			Handler:    _GoTaskService_InsertToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/task.proto",
}
